
# Base config
project_id = "ioyfxcceheflwshhaqhk"
supabase_version = "1"

# Deployment of Edge Functions
[functions.identify-fish]
verify_jwt = true # Requires authentication by default, can be set to false if called anonymously

# Enable this to run `supabase start`
[inbucket]
port = 54324
smtp_addr = "0.0.0.0"
pop3_addr = "0.0.0.0"

# db push creates new roles with a random password.
# Reset the password to a known value, used by local PostgREST.
[gotrue.database]
  user = "supabase_auth_admin"
  password = "password" # do not change unless you also change it in the .env file
  host = "localhost"
  port = 54322 # from db.docker.port in supabase/config.toml
  pooled = false # set this to true for production workloads

# Email auth
[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false # Set to false for easier local dev. Enable for production.

# External OAuth providers
[auth.external.apple]
enabled = false
client_id = ""
secret = ""

[auth.external.azure]
enabled = false
client_id = ""
secret = ""
url = ""

[auth.external.bitbucket]
enabled = false
client_id = ""
secret = ""

[auth.external.discord]
enabled = false
client_id = ""
secret = ""

[auth.external.facebook]
enabled = false
client_id = ""
secret = ""

[auth.external.figma]
enabled = false
client_id = ""
secret = ""

[auth.external.github]
enabled = false
client_id = ""
secret = ""

[auth.external.gitlab]
enabled = false
client_id = ""
secret = ""
url = ""

[auth.external.google]
enabled = false
client_id = ""
secret = ""

[auth.external.kakao]
enabled = false
client_id = ""
secret = ""

[auth.external.keycloak]
enabled = false
client_id = ""
secret = ""
url = ""

[auth.external.linkedin]
enabled = false
client_id = ""
secret = ""

[auth.external.notion]
enabled = false
client_id = ""
secret = ""

[auth.external.spotify]
enabled = false
client_id = ""
secret = ""

[auth.external.slack]
enabled = false
client_id = ""
secret = ""

[auth.external.twitch]
enabled = false
client_id = ""
secret = ""

[auth.external.twitter]
enabled = false
client_id = ""
secret = ""

[auth.external.workos]
enabled = false
client_id = ""
secret = ""
url = ""

# Phone auth
[auth.phone]
enable_signup = false

# SMS provider
[auth.sms.twilio]
enabled = false
account_sid = ""
message_service_sid = ""
auth_token = ""

[auth.sms.textlocal]
enabled = false
api_key = ""
sender = ""

[auth.sms.vonage]
enabled = false
api_key = ""
api_secret = ""

[auth.sms.messagebird]
enabled = false
access_key = ""
 originator = ""

[auth.rate_limits.email_sent]
limit = 30 # per hour
