// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ioyfxcceheflwshhaqhk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlveWZ4Y2NlaGVmbHdzaGhhcWhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNzY2MDksImV4cCI6MjA2Mzc1MjYwOX0.me3szuBGo5DUtXcQZWCib5G1GNl4DhhGiwNUSoyVTKM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);